// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Alert struct {
	ID             uuid.UUID             `json:"id"`
	Domain         string                `json:"domain"`
	EntityType     string                `json:"entity_type"`
	EntityID       string                `json:"entity_id"`
	FeederID       sql.NullString        `json:"feeder_id"`
	Type           string                `json:"type"`
	Severity       string                `json:"severity"`
	Message        string                `json:"message"`
	Metadata       pqtype.NullRawMessage `json:"metadata"`
	Fingerprint    string                `json:"fingerprint"`
	Status         string                `json:"status"`
	CreatedAt      time.Time             `json:"created_at"`
	AcknowledgedAt sql.NullTime          `json:"acknowledged_at"`
	AcknowledgedBy uuid.NullUUID         `json:"acknowledged_by"`
	ResolvedAt     sql.NullTime          `json:"resolved_at"`
	SearchText     sql.NullString        `json:"search_text"`
	Embedding      interface{}           `json:"embedding"`
}
