// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createAlert = `-- name: CreateAlert :one
INSERT INTO alerts (
    domain, entity_type, entity_id, feeder_id, type, severity, message, metadata, fingerprint, embedding
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, domain, entity_type, entity_id, feeder_id, type, severity, message, metadata, fingerprint, status, created_at, acknowledged_at, acknowledged_by, resolved_at, search_text, embedding
`

type CreateAlertParams struct {
	Domain      string                `json:"domain"`
	EntityType  string                `json:"entity_type"`
	EntityID    string                `json:"entity_id"`
	FeederID    sql.NullString        `json:"feeder_id"`
	Type        string                `json:"type"`
	Severity    string                `json:"severity"`
	Message     string                `json:"message"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
	Fingerprint string                `json:"fingerprint"`
	Embedding   interface{}           `json:"embedding"`
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	row := q.db.QueryRowContext(ctx, createAlert,
		arg.Domain,
		arg.EntityType,
		arg.EntityID,
		arg.FeederID,
		arg.Type,
		arg.Severity,
		arg.Message,
		arg.Metadata,
		arg.Fingerprint,
		arg.Embedding,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.EntityType,
		&i.EntityID,
		&i.FeederID,
		&i.Type,
		&i.Severity,
		&i.Message,
		&i.Metadata,
		&i.Fingerprint,
		&i.Status,
		&i.CreatedAt,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
		&i.ResolvedAt,
		&i.SearchText,
		&i.Embedding,
	)
	return i, err
}

const findSimilarAlerts = `-- name: FindSimilarAlerts :many
SELECT id, domain, entity_type, entity_id, feeder_id, type, severity, message, metadata, fingerprint, status, created_at, acknowledged_at, acknowledged_by, resolved_at, search_text, embedding FROM alerts
WHERE embedding IS NOT NULL
ORDER BY embedding <-> $1
LIMIT $2
`

type FindSimilarAlertsParams struct {
	Embedding interface{} `json:"embedding"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) FindSimilarAlerts(ctx context.Context, arg FindSimilarAlertsParams) ([]Alert, error) {
	rows, err := q.db.QueryContext(ctx, findSimilarAlerts, arg.Embedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.EntityType,
			&i.EntityID,
			&i.FeederID,
			&i.Type,
			&i.Severity,
			&i.Message,
			&i.Metadata,
			&i.Fingerprint,
			&i.Status,
			&i.CreatedAt,
			&i.AcknowledgedAt,
			&i.AcknowledgedBy,
			&i.ResolvedAt,
			&i.SearchText,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlertByID = `-- name: GetAlertByID :one
SELECT id, domain, entity_type, entity_id, feeder_id, type, severity, message, metadata, fingerprint, status, created_at, acknowledged_at, acknowledged_by, resolved_at, search_text, embedding FROM alerts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAlertByID(ctx context.Context, id uuid.UUID) (Alert, error) {
	row := q.db.QueryRowContext(ctx, getAlertByID, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.EntityType,
		&i.EntityID,
		&i.FeederID,
		&i.Type,
		&i.Severity,
		&i.Message,
		&i.Metadata,
		&i.Fingerprint,
		&i.Status,
		&i.CreatedAt,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
		&i.ResolvedAt,
		&i.SearchText,
		&i.Embedding,
	)
	return i, err
}

const listActiveAlerts = `-- name: ListActiveAlerts :many
SELECT id, domain, entity_type, entity_id, feeder_id, type, severity, message, metadata, fingerprint, status, created_at, acknowledged_at, acknowledged_by, resolved_at, search_text, embedding FROM alerts
WHERE status = 'OPEN' OR status = 'ACKNOWLEDGED'
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListActiveAlertsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListActiveAlerts(ctx context.Context, arg ListActiveAlertsParams) ([]Alert, error) {
	rows, err := q.db.QueryContext(ctx, listActiveAlerts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.EntityType,
			&i.EntityID,
			&i.FeederID,
			&i.Type,
			&i.Severity,
			&i.Message,
			&i.Metadata,
			&i.Fingerprint,
			&i.Status,
			&i.CreatedAt,
			&i.AcknowledgedAt,
			&i.AcknowledgedBy,
			&i.ResolvedAt,
			&i.SearchText,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlertStatus = `-- name: UpdateAlertStatus :one
UPDATE alerts
SET 
    status = $1,
    acknowledged_at = COALESCE($2, acknowledged_at),
    acknowledged_by = COALESCE($3, acknowledged_by),
    resolved_at = COALESCE($4, resolved_at)
WHERE id = $5
RETURNING id, domain, entity_type, entity_id, feeder_id, type, severity, message, metadata, fingerprint, status, created_at, acknowledged_at, acknowledged_by, resolved_at, search_text, embedding
`

type UpdateAlertStatusParams struct {
	Status         string        `json:"status"`
	AcknowledgedAt sql.NullTime  `json:"acknowledged_at"`
	AcknowledgedBy uuid.NullUUID `json:"acknowledged_by"`
	ResolvedAt     sql.NullTime  `json:"resolved_at"`
	ID             uuid.UUID     `json:"id"`
}

func (q *Queries) UpdateAlertStatus(ctx context.Context, arg UpdateAlertStatusParams) (Alert, error) {
	row := q.db.QueryRowContext(ctx, updateAlertStatus,
		arg.Status,
		arg.AcknowledgedAt,
		arg.AcknowledgedBy,
		arg.ResolvedAt,
		arg.ID,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.EntityType,
		&i.EntityID,
		&i.FeederID,
		&i.Type,
		&i.Severity,
		&i.Message,
		&i.Metadata,
		&i.Fingerprint,
		&i.Status,
		&i.CreatedAt,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
		&i.ResolvedAt,
		&i.SearchText,
		&i.Embedding,
	)
	return i, err
}
