// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: gateway.proto

package gatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayService_GetDashboardSummary_FullMethodName     = "/gridsense.gateway.v1.GatewayService/GetDashboardSummary"
	GatewayService_GetReliabilityMetrics_FullMethodName   = "/gridsense.gateway.v1.GatewayService/GetReliabilityMetrics"
	GatewayService_StreamOperationalEvents_FullMethodName = "/gridsense.gateway.v1.GatewayService/StreamOperationalEvents"
	GatewayService_GetPriorityAreas_FullMethodName        = "/gridsense.gateway.v1.GatewayService/GetPriorityAreas"
	GatewayService_GetAreaDetail_FullMethodName           = "/gridsense.gateway.v1.GatewayService/GetAreaDetail"
	GatewayService_GetAnomalyTimeline_FullMethodName      = "/gridsense.gateway.v1.GatewayService/GetAnomalyTimeline"
	GatewayService_GetRiskForecast_FullMethodName         = "/gridsense.gateway.v1.GatewayService/GetRiskForecast"
	GatewayService_GetIntelligenceInsight_FullMethodName  = "/gridsense.gateway.v1.GatewayService/GetIntelligenceInsight"
	GatewayService_AcknowledgeAlert_FullMethodName        = "/gridsense.gateway.v1.GatewayService/AcknowledgeAlert"
	GatewayService_LogIntervention_FullMethodName         = "/gridsense.gateway.v1.GatewayService/LogIntervention"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayServiceClient interface {
	GetDashboardSummary(ctx context.Context, in *DashboardSummaryRequest, opts ...grpc.CallOption) (*DashboardSummaryResponse, error)
	GetReliabilityMetrics(ctx context.Context, in *ReliabilityMetricsRequest, opts ...grpc.CallOption) (*ReliabilityMetricsResponse, error)
	StreamOperationalEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OperationalEvent], error)
	// Newly added to satisfy GraphQL Schema requirements
	GetPriorityAreas(ctx context.Context, in *PriorityAreasRequest, opts ...grpc.CallOption) (*PriorityAreasResponse, error)
	GetAreaDetail(ctx context.Context, in *AreaDetailRequest, opts ...grpc.CallOption) (*AreaDetailResponse, error)
	GetAnomalyTimeline(ctx context.Context, in *AnomalyTimelineRequest, opts ...grpc.CallOption) (*AnomalyTimelineResponse, error)
	GetRiskForecast(ctx context.Context, in *RiskForecastRequest, opts ...grpc.CallOption) (*RiskForecastResponse, error)
	GetIntelligenceInsight(ctx context.Context, in *IntelligenceInsightRequest, opts ...grpc.CallOption) (*IntelligenceInsightResponse, error)
	// Alert management operations
	AcknowledgeAlert(ctx context.Context, in *AcknowledgeAlertRequest, opts ...grpc.CallOption) (*AcknowledgeAlertResponse, error)
	LogIntervention(ctx context.Context, in *LogInterventionRequest, opts ...grpc.CallOption) (*LogInterventionResponse, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) GetDashboardSummary(ctx context.Context, in *DashboardSummaryRequest, opts ...grpc.CallOption) (*DashboardSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DashboardSummaryResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetDashboardSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetReliabilityMetrics(ctx context.Context, in *ReliabilityMetricsRequest, opts ...grpc.CallOption) (*ReliabilityMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReliabilityMetricsResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetReliabilityMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) StreamOperationalEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OperationalEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayService_ServiceDesc.Streams[0], GatewayService_StreamOperationalEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, OperationalEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_StreamOperationalEventsClient = grpc.ServerStreamingClient[OperationalEvent]

func (c *gatewayServiceClient) GetPriorityAreas(ctx context.Context, in *PriorityAreasRequest, opts ...grpc.CallOption) (*PriorityAreasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PriorityAreasResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetPriorityAreas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetAreaDetail(ctx context.Context, in *AreaDetailRequest, opts ...grpc.CallOption) (*AreaDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AreaDetailResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetAreaDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetAnomalyTimeline(ctx context.Context, in *AnomalyTimelineRequest, opts ...grpc.CallOption) (*AnomalyTimelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnomalyTimelineResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetAnomalyTimeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetRiskForecast(ctx context.Context, in *RiskForecastRequest, opts ...grpc.CallOption) (*RiskForecastResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiskForecastResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetRiskForecast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetIntelligenceInsight(ctx context.Context, in *IntelligenceInsightRequest, opts ...grpc.CallOption) (*IntelligenceInsightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntelligenceInsightResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetIntelligenceInsight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) AcknowledgeAlert(ctx context.Context, in *AcknowledgeAlertRequest, opts ...grpc.CallOption) (*AcknowledgeAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcknowledgeAlertResponse)
	err := c.cc.Invoke(ctx, GatewayService_AcknowledgeAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) LogIntervention(ctx context.Context, in *LogInterventionRequest, opts ...grpc.CallOption) (*LogInterventionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogInterventionResponse)
	err := c.cc.Invoke(ctx, GatewayService_LogIntervention_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility.
type GatewayServiceServer interface {
	GetDashboardSummary(context.Context, *DashboardSummaryRequest) (*DashboardSummaryResponse, error)
	GetReliabilityMetrics(context.Context, *ReliabilityMetricsRequest) (*ReliabilityMetricsResponse, error)
	StreamOperationalEvents(*StreamEventsRequest, grpc.ServerStreamingServer[OperationalEvent]) error
	// Newly added to satisfy GraphQL Schema requirements
	GetPriorityAreas(context.Context, *PriorityAreasRequest) (*PriorityAreasResponse, error)
	GetAreaDetail(context.Context, *AreaDetailRequest) (*AreaDetailResponse, error)
	GetAnomalyTimeline(context.Context, *AnomalyTimelineRequest) (*AnomalyTimelineResponse, error)
	GetRiskForecast(context.Context, *RiskForecastRequest) (*RiskForecastResponse, error)
	GetIntelligenceInsight(context.Context, *IntelligenceInsightRequest) (*IntelligenceInsightResponse, error)
	// Alert management operations
	AcknowledgeAlert(context.Context, *AcknowledgeAlertRequest) (*AcknowledgeAlertResponse, error)
	LogIntervention(context.Context, *LogInterventionRequest) (*LogInterventionResponse, error)
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServiceServer struct{}

func (UnimplementedGatewayServiceServer) GetDashboardSummary(context.Context, *DashboardSummaryRequest) (*DashboardSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDashboardSummary not implemented")
}
func (UnimplementedGatewayServiceServer) GetReliabilityMetrics(context.Context, *ReliabilityMetricsRequest) (*ReliabilityMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReliabilityMetrics not implemented")
}
func (UnimplementedGatewayServiceServer) StreamOperationalEvents(*StreamEventsRequest, grpc.ServerStreamingServer[OperationalEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamOperationalEvents not implemented")
}
func (UnimplementedGatewayServiceServer) GetPriorityAreas(context.Context, *PriorityAreasRequest) (*PriorityAreasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPriorityAreas not implemented")
}
func (UnimplementedGatewayServiceServer) GetAreaDetail(context.Context, *AreaDetailRequest) (*AreaDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAreaDetail not implemented")
}
func (UnimplementedGatewayServiceServer) GetAnomalyTimeline(context.Context, *AnomalyTimelineRequest) (*AnomalyTimelineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnomalyTimeline not implemented")
}
func (UnimplementedGatewayServiceServer) GetRiskForecast(context.Context, *RiskForecastRequest) (*RiskForecastResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRiskForecast not implemented")
}
func (UnimplementedGatewayServiceServer) GetIntelligenceInsight(context.Context, *IntelligenceInsightRequest) (*IntelligenceInsightResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIntelligenceInsight not implemented")
}
func (UnimplementedGatewayServiceServer) AcknowledgeAlert(context.Context, *AcknowledgeAlertRequest) (*AcknowledgeAlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcknowledgeAlert not implemented")
}
func (UnimplementedGatewayServiceServer) LogIntervention(context.Context, *LogInterventionRequest) (*LogInterventionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LogIntervention not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}
func (UnimplementedGatewayServiceServer) testEmbeddedByValue()                        {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_GetDashboardSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DashboardSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetDashboardSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetDashboardSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetDashboardSummary(ctx, req.(*DashboardSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetReliabilityMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReliabilityMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetReliabilityMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetReliabilityMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetReliabilityMetrics(ctx, req.(*ReliabilityMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_StreamOperationalEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatewayServiceServer).StreamOperationalEvents(m, &grpc.GenericServerStream[StreamEventsRequest, OperationalEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_StreamOperationalEventsServer = grpc.ServerStreamingServer[OperationalEvent]

func _GatewayService_GetPriorityAreas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PriorityAreasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetPriorityAreas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetPriorityAreas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetPriorityAreas(ctx, req.(*PriorityAreasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetAreaDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AreaDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetAreaDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetAreaDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetAreaDetail(ctx, req.(*AreaDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetAnomalyTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnomalyTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetAnomalyTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetAnomalyTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetAnomalyTimeline(ctx, req.(*AnomalyTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetRiskForecast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RiskForecastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetRiskForecast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetRiskForecast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetRiskForecast(ctx, req.(*RiskForecastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetIntelligenceInsight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntelligenceInsightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetIntelligenceInsight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetIntelligenceInsight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetIntelligenceInsight(ctx, req.(*IntelligenceInsightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_AcknowledgeAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).AcknowledgeAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_AcknowledgeAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).AcknowledgeAlert(ctx, req.(*AcknowledgeAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_LogIntervention_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogInterventionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).LogIntervention(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_LogIntervention_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).LogIntervention(ctx, req.(*LogInterventionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gridsense.gateway.v1.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDashboardSummary",
			Handler:    _GatewayService_GetDashboardSummary_Handler,
		},
		{
			MethodName: "GetReliabilityMetrics",
			Handler:    _GatewayService_GetReliabilityMetrics_Handler,
		},
		{
			MethodName: "GetPriorityAreas",
			Handler:    _GatewayService_GetPriorityAreas_Handler,
		},
		{
			MethodName: "GetAreaDetail",
			Handler:    _GatewayService_GetAreaDetail_Handler,
		},
		{
			MethodName: "GetAnomalyTimeline",
			Handler:    _GatewayService_GetAnomalyTimeline_Handler,
		},
		{
			MethodName: "GetRiskForecast",
			Handler:    _GatewayService_GetRiskForecast_Handler,
		},
		{
			MethodName: "GetIntelligenceInsight",
			Handler:    _GatewayService_GetIntelligenceInsight_Handler,
		},
		{
			MethodName: "AcknowledgeAlert",
			Handler:    _GatewayService_AcknowledgeAlert_Handler,
		},
		{
			MethodName: "LogIntervention",
			Handler:    _GatewayService_LogIntervention_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamOperationalEvents",
			Handler:       _GatewayService_StreamOperationalEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gateway.proto",
}
