// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: proto/gateway.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DashboardSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeRange     string                 `protobuf:"bytes,1,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardSummaryRequest) Reset() {
	*x = DashboardSummaryRequest{}
	mi := &file_proto_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardSummaryRequest) ProtoMessage() {}

func (x *DashboardSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardSummaryRequest.ProtoReflect.Descriptor instead.
func (*DashboardSummaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *DashboardSummaryRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

type DashboardSummaryResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	OverallReliabilityScore float64                `protobuf:"fixed64,1,opt,name=overall_reliability_score,json=overallReliabilityScore,proto3" json:"overall_reliability_score,omitempty"`
	ActiveHighRiskAreas     int32                  `protobuf:"varint,2,opt,name=active_high_risk_areas,json=activeHighRiskAreas,proto3" json:"active_high_risk_areas,omitempty"`
	TotalActiveAlerts       int32                  `protobuf:"varint,3,opt,name=total_active_alerts,json=totalActiveAlerts,proto3" json:"total_active_alerts,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *DashboardSummaryResponse) Reset() {
	*x = DashboardSummaryResponse{}
	mi := &file_proto_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardSummaryResponse) ProtoMessage() {}

func (x *DashboardSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardSummaryResponse.ProtoReflect.Descriptor instead.
func (*DashboardSummaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *DashboardSummaryResponse) GetOverallReliabilityScore() float64 {
	if x != nil {
		return x.OverallReliabilityScore
	}
	return 0
}

func (x *DashboardSummaryResponse) GetActiveHighRiskAreas() int32 {
	if x != nil {
		return x.ActiveHighRiskAreas
	}
	return 0
}

func (x *DashboardSummaryResponse) GetTotalActiveAlerts() int32 {
	if x != nil {
		return x.TotalActiveAlerts
	}
	return 0
}

type ReliabilityMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AreaId        string                 `protobuf:"bytes,1,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	TimeRange     string                 `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReliabilityMetricsRequest) Reset() {
	*x = ReliabilityMetricsRequest{}
	mi := &file_proto_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReliabilityMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReliabilityMetricsRequest) ProtoMessage() {}

func (x *ReliabilityMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReliabilityMetricsRequest.ProtoReflect.Descriptor instead.
func (*ReliabilityMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *ReliabilityMetricsRequest) GetAreaId() string {
	if x != nil {
		return x.AreaId
	}
	return ""
}

func (x *ReliabilityMetricsRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

type ReliabilityMetricsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AreaId           string                 `protobuf:"bytes,1,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	CurrentRiskScore float64                `protobuf:"fixed64,2,opt,name=current_risk_score,json=currentRiskScore,proto3" json:"current_risk_score,omitempty"`
	Trend            []*TrendDataPoint      `protobuf:"bytes,3,rep,name=trend,proto3" json:"trend,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReliabilityMetricsResponse) Reset() {
	*x = ReliabilityMetricsResponse{}
	mi := &file_proto_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReliabilityMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReliabilityMetricsResponse) ProtoMessage() {}

func (x *ReliabilityMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReliabilityMetricsResponse.ProtoReflect.Descriptor instead.
func (*ReliabilityMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *ReliabilityMetricsResponse) GetAreaId() string {
	if x != nil {
		return x.AreaId
	}
	return ""
}

func (x *ReliabilityMetricsResponse) GetCurrentRiskScore() float64 {
	if x != nil {
		return x.CurrentRiskScore
	}
	return 0
}

func (x *ReliabilityMetricsResponse) GetTrend() []*TrendDataPoint {
	if x != nil {
		return x.Trend
	}
	return nil
}

type TrendDataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendDataPoint) Reset() {
	*x = TrendDataPoint{}
	mi := &file_proto_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendDataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendDataPoint) ProtoMessage() {}

func (x *TrendDataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendDataPoint.ProtoReflect.Descriptor instead.
func (*TrendDataPoint) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *TrendDataPoint) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *TrendDataPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AreaIds       []string               `protobuf:"bytes,1,rep,name=area_ids,json=areaIds,proto3" json:"area_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_proto_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *StreamEventsRequest) GetAreaIds() []string {
	if x != nil {
		return x.AreaIds
	}
	return nil
}

type OperationalEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	AreaId        string                 `protobuf:"bytes,2,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationalEvent) Reset() {
	*x = OperationalEvent{}
	mi := &file_proto_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationalEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationalEvent) ProtoMessage() {}

func (x *OperationalEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationalEvent.ProtoReflect.Descriptor instead.
func (*OperationalEvent) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *OperationalEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *OperationalEvent) GetAreaId() string {
	if x != nil {
		return x.AreaId
	}
	return ""
}

func (x *OperationalEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *OperationalEvent) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *OperationalEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *OperationalEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PriorityAreasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriorityAreasRequest) Reset() {
	*x = PriorityAreasRequest{}
	mi := &file_proto_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriorityAreasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriorityAreasRequest) ProtoMessage() {}

func (x *PriorityAreasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriorityAreasRequest.ProtoReflect.Descriptor instead.
func (*PriorityAreasRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{7}
}

type PriorityAreasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Areas         []*PriorityArea        `protobuf:"bytes,1,rep,name=areas,proto3" json:"areas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriorityAreasResponse) Reset() {
	*x = PriorityAreasResponse{}
	mi := &file_proto_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriorityAreasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriorityAreasResponse) ProtoMessage() {}

func (x *PriorityAreasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriorityAreasResponse.ProtoReflect.Descriptor instead.
func (*PriorityAreasResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *PriorityAreasResponse) GetAreas() []*PriorityArea {
	if x != nil {
		return x.Areas
	}
	return nil
}

type PriorityArea struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UrgencyRank   int32                  `protobuf:"varint,3,opt,name=urgency_rank,json=urgencyRank,proto3" json:"urgency_rank,omitempty"`
	RiskScore     float64                `protobuf:"fixed64,4,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriorityArea) Reset() {
	*x = PriorityArea{}
	mi := &file_proto_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriorityArea) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriorityArea) ProtoMessage() {}

func (x *PriorityArea) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriorityArea.ProtoReflect.Descriptor instead.
func (*PriorityArea) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *PriorityArea) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PriorityArea) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PriorityArea) GetUrgencyRank() int32 {
	if x != nil {
		return x.UrgencyRank
	}
	return 0
}

func (x *PriorityArea) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *PriorityArea) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AreaDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AreaDetailRequest) Reset() {
	*x = AreaDetailRequest{}
	mi := &file_proto_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AreaDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreaDetailRequest) ProtoMessage() {}

func (x *AreaDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreaDetailRequest.ProtoReflect.Descriptor instead.
func (*AreaDetailRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *AreaDetailRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AreaDetailResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CurrentRiskScore float64                `protobuf:"fixed64,3,opt,name=current_risk_score,json=currentRiskScore,proto3" json:"current_risk_score,omitempty"`
	Status           string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AreaDetailResponse) Reset() {
	*x = AreaDetailResponse{}
	mi := &file_proto_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AreaDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreaDetailResponse) ProtoMessage() {}

func (x *AreaDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreaDetailResponse.ProtoReflect.Descriptor instead.
func (*AreaDetailResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *AreaDetailResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AreaDetailResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AreaDetailResponse) GetCurrentRiskScore() float64 {
	if x != nil {
		return x.CurrentRiskScore
	}
	return 0
}

func (x *AreaDetailResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AnomalyTimelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AreaId        string                 `protobuf:"bytes,1,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnomalyTimelineRequest) Reset() {
	*x = AnomalyTimelineRequest{}
	mi := &file_proto_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnomalyTimelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnomalyTimelineRequest) ProtoMessage() {}

func (x *AnomalyTimelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnomalyTimelineRequest.ProtoReflect.Descriptor instead.
func (*AnomalyTimelineRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *AnomalyTimelineRequest) GetAreaId() string {
	if x != nil {
		return x.AreaId
	}
	return ""
}

type AnomalyTimelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*OperationalEvent    `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnomalyTimelineResponse) Reset() {
	*x = AnomalyTimelineResponse{}
	mi := &file_proto_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnomalyTimelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnomalyTimelineResponse) ProtoMessage() {}

func (x *AnomalyTimelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnomalyTimelineResponse.ProtoReflect.Descriptor instead.
func (*AnomalyTimelineResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{13}
}

func (x *AnomalyTimelineResponse) GetEvents() []*OperationalEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type RiskForecastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AreaId        string                 `protobuf:"bytes,1,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskForecastRequest) Reset() {
	*x = RiskForecastRequest{}
	mi := &file_proto_gateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskForecastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskForecastRequest) ProtoMessage() {}

func (x *RiskForecastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskForecastRequest.ProtoReflect.Descriptor instead.
func (*RiskForecastRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{14}
}

func (x *RiskForecastRequest) GetAreaId() string {
	if x != nil {
		return x.AreaId
	}
	return ""
}

type RiskForecastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*RiskForecastPoint   `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskForecastResponse) Reset() {
	*x = RiskForecastResponse{}
	mi := &file_proto_gateway_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskForecastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskForecastResponse) ProtoMessage() {}

func (x *RiskForecastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskForecastResponse.ProtoReflect.Descriptor instead.
func (*RiskForecastResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{15}
}

func (x *RiskForecastResponse) GetPoints() []*RiskForecastPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type RiskForecastPoint struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Timestamp          string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PredictedRiskScore float64                `protobuf:"fixed64,2,opt,name=predicted_risk_score,json=predictedRiskScore,proto3" json:"predicted_risk_score,omitempty"`
	IsHistorical       bool                   `protobuf:"varint,3,opt,name=is_historical,json=isHistorical,proto3" json:"is_historical,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RiskForecastPoint) Reset() {
	*x = RiskForecastPoint{}
	mi := &file_proto_gateway_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskForecastPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskForecastPoint) ProtoMessage() {}

func (x *RiskForecastPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskForecastPoint.ProtoReflect.Descriptor instead.
func (*RiskForecastPoint) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{16}
}

func (x *RiskForecastPoint) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *RiskForecastPoint) GetPredictedRiskScore() float64 {
	if x != nil {
		return x.PredictedRiskScore
	}
	return 0
}

func (x *RiskForecastPoint) GetIsHistorical() bool {
	if x != nil {
		return x.IsHistorical
	}
	return false
}

type IntelligenceInsightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnomalyId     string                 `protobuf:"bytes,1,opt,name=anomaly_id,json=anomalyId,proto3" json:"anomaly_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntelligenceInsightRequest) Reset() {
	*x = IntelligenceInsightRequest{}
	mi := &file_proto_gateway_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntelligenceInsightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntelligenceInsightRequest) ProtoMessage() {}

func (x *IntelligenceInsightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntelligenceInsightRequest.ProtoReflect.Descriptor instead.
func (*IntelligenceInsightRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{17}
}

func (x *IntelligenceInsightRequest) GetAnomalyId() string {
	if x != nil {
		return x.AnomalyId
	}
	return ""
}

type IntelligenceInsightResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AnomalyId         string                 `protobuf:"bytes,1,opt,name=anomaly_id,json=anomalyId,proto3" json:"anomaly_id,omitempty"`
	ConfidenceScore   float64                `protobuf:"fixed64,2,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	Reasons           []string               `protobuf:"bytes,3,rep,name=reasons,proto3" json:"reasons,omitempty"`
	FeatureDeviations []*FeatureDeviation    `protobuf:"bytes,4,rep,name=feature_deviations,json=featureDeviations,proto3" json:"feature_deviations,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IntelligenceInsightResponse) Reset() {
	*x = IntelligenceInsightResponse{}
	mi := &file_proto_gateway_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntelligenceInsightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntelligenceInsightResponse) ProtoMessage() {}

func (x *IntelligenceInsightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntelligenceInsightResponse.ProtoReflect.Descriptor instead.
func (*IntelligenceInsightResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{18}
}

func (x *IntelligenceInsightResponse) GetAnomalyId() string {
	if x != nil {
		return x.AnomalyId
	}
	return ""
}

func (x *IntelligenceInsightResponse) GetConfidenceScore() float64 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *IntelligenceInsightResponse) GetReasons() []string {
	if x != nil {
		return x.Reasons
	}
	return nil
}

func (x *IntelligenceInsightResponse) GetFeatureDeviations() []*FeatureDeviation {
	if x != nil {
		return x.FeatureDeviations
	}
	return nil
}

type FeatureDeviation struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	FeatureName          string                 `protobuf:"bytes,1,opt,name=feature_name,json=featureName,proto3" json:"feature_name,omitempty"`
	ShapAttribution      float64                `protobuf:"fixed64,2,opt,name=shap_attribution,json=shapAttribution,proto3" json:"shap_attribution,omitempty"`
	DeviationDescription string                 `protobuf:"bytes,3,opt,name=deviation_description,json=deviationDescription,proto3" json:"deviation_description,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FeatureDeviation) Reset() {
	*x = FeatureDeviation{}
	mi := &file_proto_gateway_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureDeviation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureDeviation) ProtoMessage() {}

func (x *FeatureDeviation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureDeviation.ProtoReflect.Descriptor instead.
func (*FeatureDeviation) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{19}
}

func (x *FeatureDeviation) GetFeatureName() string {
	if x != nil {
		return x.FeatureName
	}
	return ""
}

func (x *FeatureDeviation) GetShapAttribution() float64 {
	if x != nil {
		return x.ShapAttribution
	}
	return 0
}

func (x *FeatureDeviation) GetDeviationDescription() string {
	if x != nil {
		return x.DeviationDescription
	}
	return ""
}

var File_proto_gateway_proto protoreflect.FileDescriptor

const file_proto_gateway_proto_rawDesc = "" +
	"\n" +
	"\x13proto/gateway.proto\x12\x14gridsense.gateway.v1\"8\n" +
	"\x17DashboardSummaryRequest\x12\x1d\n" +
	"\n" +
	"time_range\x18\x01 \x01(\tR\ttimeRange\"\xbb\x01\n" +
	"\x18DashboardSummaryResponse\x12:\n" +
	"\x19overall_reliability_score\x18\x01 \x01(\x01R\x17overallReliabilityScore\x123\n" +
	"\x16active_high_risk_areas\x18\x02 \x01(\x05R\x13activeHighRiskAreas\x12.\n" +
	"\x13total_active_alerts\x18\x03 \x01(\x05R\x11totalActiveAlerts\"S\n" +
	"\x19ReliabilityMetricsRequest\x12\x17\n" +
	"\aarea_id\x18\x01 \x01(\tR\x06areaId\x12\x1d\n" +
	"\n" +
	"time_range\x18\x02 \x01(\tR\ttimeRange\"\x9f\x01\n" +
	"\x1aReliabilityMetricsResponse\x12\x17\n" +
	"\aarea_id\x18\x01 \x01(\tR\x06areaId\x12,\n" +
	"\x12current_risk_score\x18\x02 \x01(\x01R\x10currentRiskScore\x12:\n" +
	"\x05trend\x18\x03 \x03(\v2$.gridsense.gateway.v1.TrendDataPointR\x05trend\"D\n" +
	"\x0eTrendDataPoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"0\n" +
	"\x13StreamEventsRequest\x12\x19\n" +
	"\barea_ids\x18\x01 \x03(\tR\aareaIds\"\xc1\x01\n" +
	"\x10OperationalEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\aarea_id\x18\x02 \x01(\tR\x06areaId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"\x16\n" +
	"\x14PriorityAreasRequest\"Q\n" +
	"\x15PriorityAreasResponse\x128\n" +
	"\x05areas\x18\x01 \x03(\v2\".gridsense.gateway.v1.PriorityAreaR\x05areas\"\x8c\x01\n" +
	"\fPriorityArea\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\furgency_rank\x18\x03 \x01(\x05R\vurgencyRank\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x04 \x01(\x01R\triskScore\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"#\n" +
	"\x11AreaDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"~\n" +
	"\x12AreaDetailResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\x12current_risk_score\x18\x03 \x01(\x01R\x10currentRiskScore\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"1\n" +
	"\x16AnomalyTimelineRequest\x12\x17\n" +
	"\aarea_id\x18\x01 \x01(\tR\x06areaId\"Y\n" +
	"\x17AnomalyTimelineResponse\x12>\n" +
	"\x06events\x18\x01 \x03(\v2&.gridsense.gateway.v1.OperationalEventR\x06events\".\n" +
	"\x13RiskForecastRequest\x12\x17\n" +
	"\aarea_id\x18\x01 \x01(\tR\x06areaId\"W\n" +
	"\x14RiskForecastResponse\x12?\n" +
	"\x06points\x18\x01 \x03(\v2'.gridsense.gateway.v1.RiskForecastPointR\x06points\"\x88\x01\n" +
	"\x11RiskForecastPoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x120\n" +
	"\x14predicted_risk_score\x18\x02 \x01(\x01R\x12predictedRiskScore\x12#\n" +
	"\ris_historical\x18\x03 \x01(\bR\fisHistorical\";\n" +
	"\x1aIntelligenceInsightRequest\x12\x1d\n" +
	"\n" +
	"anomaly_id\x18\x01 \x01(\tR\tanomalyId\"\xd8\x01\n" +
	"\x1bIntelligenceInsightResponse\x12\x1d\n" +
	"\n" +
	"anomaly_id\x18\x01 \x01(\tR\tanomalyId\x12)\n" +
	"\x10confidence_score\x18\x02 \x01(\x01R\x0fconfidenceScore\x12\x18\n" +
	"\areasons\x18\x03 \x03(\tR\areasons\x12U\n" +
	"\x12feature_deviations\x18\x04 \x03(\v2&.gridsense.gateway.v1.FeatureDeviationR\x11featureDeviations\"\x95\x01\n" +
	"\x10FeatureDeviation\x12!\n" +
	"\ffeature_name\x18\x01 \x01(\tR\vfeatureName\x12)\n" +
	"\x10shap_attribution\x18\x02 \x01(\x01R\x0fshapAttribution\x123\n" +
	"\x15deviation_description\x18\x03 \x01(\tR\x14deviationDescription2\x9f\a\n" +
	"\x0eGatewayService\x12t\n" +
	"\x13GetDashboardSummary\x12-.gridsense.gateway.v1.DashboardSummaryRequest\x1a..gridsense.gateway.v1.DashboardSummaryResponse\x12z\n" +
	"\x15GetReliabilityMetrics\x12/.gridsense.gateway.v1.ReliabilityMetricsRequest\x1a0.gridsense.gateway.v1.ReliabilityMetricsResponse\x12n\n" +
	"\x17StreamOperationalEvents\x12).gridsense.gateway.v1.StreamEventsRequest\x1a&.gridsense.gateway.v1.OperationalEvent0\x01\x12k\n" +
	"\x10GetPriorityAreas\x12*.gridsense.gateway.v1.PriorityAreasRequest\x1a+.gridsense.gateway.v1.PriorityAreasResponse\x12b\n" +
	"\rGetAreaDetail\x12'.gridsense.gateway.v1.AreaDetailRequest\x1a(.gridsense.gateway.v1.AreaDetailResponse\x12q\n" +
	"\x12GetAnomalyTimeline\x12,.gridsense.gateway.v1.AnomalyTimelineRequest\x1a-.gridsense.gateway.v1.AnomalyTimelineResponse\x12h\n" +
	"\x0fGetRiskForecast\x12).gridsense.gateway.v1.RiskForecastRequest\x1a*.gridsense.gateway.v1.RiskForecastResponse\x12}\n" +
	"\x16GetIntelligenceInsight\x120.gridsense.gateway.v1.IntelligenceInsightRequest\x1a1.gridsense.gateway.v1.IntelligenceInsightResponseBLZJgridsense-ai/backend/services/dashboard-bff/proto/gen/gateway/v1;gatewayv1b\x06proto3"

var (
	file_proto_gateway_proto_rawDescOnce sync.Once
	file_proto_gateway_proto_rawDescData []byte
)

func file_proto_gateway_proto_rawDescGZIP() []byte {
	file_proto_gateway_proto_rawDescOnce.Do(func() {
		file_proto_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gateway_proto_rawDesc), len(file_proto_gateway_proto_rawDesc)))
	})
	return file_proto_gateway_proto_rawDescData
}

var file_proto_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_gateway_proto_goTypes = []any{
	(*DashboardSummaryRequest)(nil),     // 0: gridsense.gateway.v1.DashboardSummaryRequest
	(*DashboardSummaryResponse)(nil),    // 1: gridsense.gateway.v1.DashboardSummaryResponse
	(*ReliabilityMetricsRequest)(nil),   // 2: gridsense.gateway.v1.ReliabilityMetricsRequest
	(*ReliabilityMetricsResponse)(nil),  // 3: gridsense.gateway.v1.ReliabilityMetricsResponse
	(*TrendDataPoint)(nil),              // 4: gridsense.gateway.v1.TrendDataPoint
	(*StreamEventsRequest)(nil),         // 5: gridsense.gateway.v1.StreamEventsRequest
	(*OperationalEvent)(nil),            // 6: gridsense.gateway.v1.OperationalEvent
	(*PriorityAreasRequest)(nil),        // 7: gridsense.gateway.v1.PriorityAreasRequest
	(*PriorityAreasResponse)(nil),       // 8: gridsense.gateway.v1.PriorityAreasResponse
	(*PriorityArea)(nil),                // 9: gridsense.gateway.v1.PriorityArea
	(*AreaDetailRequest)(nil),           // 10: gridsense.gateway.v1.AreaDetailRequest
	(*AreaDetailResponse)(nil),          // 11: gridsense.gateway.v1.AreaDetailResponse
	(*AnomalyTimelineRequest)(nil),      // 12: gridsense.gateway.v1.AnomalyTimelineRequest
	(*AnomalyTimelineResponse)(nil),     // 13: gridsense.gateway.v1.AnomalyTimelineResponse
	(*RiskForecastRequest)(nil),         // 14: gridsense.gateway.v1.RiskForecastRequest
	(*RiskForecastResponse)(nil),        // 15: gridsense.gateway.v1.RiskForecastResponse
	(*RiskForecastPoint)(nil),           // 16: gridsense.gateway.v1.RiskForecastPoint
	(*IntelligenceInsightRequest)(nil),  // 17: gridsense.gateway.v1.IntelligenceInsightRequest
	(*IntelligenceInsightResponse)(nil), // 18: gridsense.gateway.v1.IntelligenceInsightResponse
	(*FeatureDeviation)(nil),            // 19: gridsense.gateway.v1.FeatureDeviation
}
var file_proto_gateway_proto_depIdxs = []int32{
	4,  // 0: gridsense.gateway.v1.ReliabilityMetricsResponse.trend:type_name -> gridsense.gateway.v1.TrendDataPoint
	9,  // 1: gridsense.gateway.v1.PriorityAreasResponse.areas:type_name -> gridsense.gateway.v1.PriorityArea
	6,  // 2: gridsense.gateway.v1.AnomalyTimelineResponse.events:type_name -> gridsense.gateway.v1.OperationalEvent
	16, // 3: gridsense.gateway.v1.RiskForecastResponse.points:type_name -> gridsense.gateway.v1.RiskForecastPoint
	19, // 4: gridsense.gateway.v1.IntelligenceInsightResponse.feature_deviations:type_name -> gridsense.gateway.v1.FeatureDeviation
	0,  // 5: gridsense.gateway.v1.GatewayService.GetDashboardSummary:input_type -> gridsense.gateway.v1.DashboardSummaryRequest
	2,  // 6: gridsense.gateway.v1.GatewayService.GetReliabilityMetrics:input_type -> gridsense.gateway.v1.ReliabilityMetricsRequest
	5,  // 7: gridsense.gateway.v1.GatewayService.StreamOperationalEvents:input_type -> gridsense.gateway.v1.StreamEventsRequest
	7,  // 8: gridsense.gateway.v1.GatewayService.GetPriorityAreas:input_type -> gridsense.gateway.v1.PriorityAreasRequest
	10, // 9: gridsense.gateway.v1.GatewayService.GetAreaDetail:input_type -> gridsense.gateway.v1.AreaDetailRequest
	12, // 10: gridsense.gateway.v1.GatewayService.GetAnomalyTimeline:input_type -> gridsense.gateway.v1.AnomalyTimelineRequest
	14, // 11: gridsense.gateway.v1.GatewayService.GetRiskForecast:input_type -> gridsense.gateway.v1.RiskForecastRequest
	17, // 12: gridsense.gateway.v1.GatewayService.GetIntelligenceInsight:input_type -> gridsense.gateway.v1.IntelligenceInsightRequest
	1,  // 13: gridsense.gateway.v1.GatewayService.GetDashboardSummary:output_type -> gridsense.gateway.v1.DashboardSummaryResponse
	3,  // 14: gridsense.gateway.v1.GatewayService.GetReliabilityMetrics:output_type -> gridsense.gateway.v1.ReliabilityMetricsResponse
	6,  // 15: gridsense.gateway.v1.GatewayService.StreamOperationalEvents:output_type -> gridsense.gateway.v1.OperationalEvent
	8,  // 16: gridsense.gateway.v1.GatewayService.GetPriorityAreas:output_type -> gridsense.gateway.v1.PriorityAreasResponse
	11, // 17: gridsense.gateway.v1.GatewayService.GetAreaDetail:output_type -> gridsense.gateway.v1.AreaDetailResponse
	13, // 18: gridsense.gateway.v1.GatewayService.GetAnomalyTimeline:output_type -> gridsense.gateway.v1.AnomalyTimelineResponse
	15, // 19: gridsense.gateway.v1.GatewayService.GetRiskForecast:output_type -> gridsense.gateway.v1.RiskForecastResponse
	18, // 20: gridsense.gateway.v1.GatewayService.GetIntelligenceInsight:output_type -> gridsense.gateway.v1.IntelligenceInsightResponse
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_gateway_proto_init() }
func file_proto_gateway_proto_init() {
	if File_proto_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gateway_proto_rawDesc), len(file_proto_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gateway_proto_goTypes,
		DependencyIndexes: file_proto_gateway_proto_depIdxs,
		MessageInfos:      file_proto_gateway_proto_msgTypes,
	}.Build()
	File_proto_gateway_proto = out.File
	file_proto_gateway_proto_goTypes = nil
	file_proto_gateway_proto_depIdxs = nil
}
