package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"
	"gridsense-ai/backend/services/dashboard-bff/graph/generated"
	"gridsense-ai/backend/services/dashboard-bff/graph/model"
	pb "gridsense-ai/backend/services/dashboard-bff/proto/gen/gateway/v1/proto"
)

// AcknowledgeAlert is the resolver for the acknowledgeAlert field.
func (r *mutationResolver) AcknowledgeAlert(ctx context.Context, alertID string, notes *string) (*model.AcknowledgeAlertResult, error) {
	panic(fmt.Errorf("not implemented: AcknowledgeAlert - acknowledgeAlert"))
}

// LogIntervention is the resolver for the logIntervention field.
func (r *mutationResolver) LogIntervention(ctx context.Context, alertID string, feederID string, actionTaken string, notes *string) (*model.LogInterventionResult, error) {
	panic(fmt.Errorf("not implemented: LogIntervention - logIntervention"))
}

// DashboardSummary is the resolver for the dashboardSummary field.
func (r *queryResolver) DashboardSummary(ctx context.Context, timeRange string) (*model.DashboardSummary, error) {
	req := &pb.DashboardSummaryRequest{TimeRange: timeRange}
	res, err := r.GatewayClient.Client.GetDashboardSummary(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get dashboard summary: %w", err)
	}

	return &model.DashboardSummary{
		OverallReliabilityScore: res.OverallReliabilityScore,
		ActiveHighRiskAreas:     int(res.ActiveHighRiskAreas),
		TotalActiveAlerts:       int(res.TotalActiveAlerts),
	}, nil
}

// PriorityAreas is the resolver for the priorityAreas field.
func (r *queryResolver) PriorityAreas(ctx context.Context) ([]*model.PriorityArea, error) {
	req := &pb.PriorityAreasRequest{}
	res, err := r.GatewayClient.Client.GetPriorityAreas(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get priority areas: %w", err)
	}

	var areas []*model.PriorityArea
	for _, a := range res.Areas {
		areas = append(areas, &model.PriorityArea{
			ID:          a.Id,
			Name:        a.Name,
			UrgencyRank: int(a.UrgencyRank),
			RiskScore:   a.RiskScore,
			Status:      a.Status,
		})
	}
	return areas, nil
}

// ReliabilityTrend is the resolver for the reliabilityTrend field.
func (r *queryResolver) ReliabilityTrend(ctx context.Context, timeRange string) ([]*model.TrendDataPoint, error) {
	req := &pb.ReliabilityMetricsRequest{
		AreaId:    "global", // Defaulting to global for the system-wide trend
		TimeRange: timeRange,
	}
	res, err := r.GatewayClient.Client.GetReliabilityMetrics(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get reliability trend: %w", err)
	}

	var trend []*model.TrendDataPoint
	for _, p := range res.Trend {
		trend = append(trend, &model.TrendDataPoint{
			Timestamp: p.Timestamp,
			Value:     p.Value,
		})
	}
	return trend, nil
}

// AreaDetail is the resolver for the areaDetail field.
func (r *queryResolver) AreaDetail(ctx context.Context, id string) (*model.AreaDetail, error) {
	req := &pb.AreaDetailRequest{Id: id}
	res, err := r.GatewayClient.Client.GetAreaDetail(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get area detail: %w", err)
	}

	return &model.AreaDetail{
		ID:               res.Id,
		Name:             res.Name,
		CurrentRiskScore: res.CurrentRiskScore,
		Status:           res.Status,
	}, nil
}

// AnomalyTimeline is the resolver for the anomalyTimeline field.
func (r *queryResolver) AnomalyTimeline(ctx context.Context, areaID string) ([]*model.AnomalyEvent, error) {
	req := &pb.AnomalyTimelineRequest{AreaId: areaID}
	res, err := r.GatewayClient.Client.GetAnomalyTimeline(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get anomaly timeline: %w", err)
	}

	var events []*model.AnomalyEvent
	for _, e := range res.Events {
		events = append(events, &model.AnomalyEvent{
			ID:          e.EventId,
			AreaID:      e.AreaId,
			EventType:   e.EventType,
			Severity:    e.Severity,
			Timestamp:   e.Timestamp,
			Description: e.Description,
		})
	}
	return events, nil
}

// RiskForecast is the resolver for the riskForecast field.
func (r *queryResolver) RiskForecast(ctx context.Context, areaID string) ([]*model.RiskForecastPoint, error) {
	req := &pb.RiskForecastRequest{AreaId: areaID}
	res, err := r.GatewayClient.Client.GetRiskForecast(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get risk forecast: %w", err)
	}

	var points []*model.RiskForecastPoint
	for _, p := range res.Points {
		points = append(points, &model.RiskForecastPoint{
			Timestamp:          p.Timestamp,
			PredictedRiskScore: p.PredictedRiskScore,
			IsHistorical:       p.IsHistorical,
		})
	}
	return points, nil
}

// IntelligenceInsight is the resolver for the intelligenceInsight field.
func (r *queryResolver) IntelligenceInsight(ctx context.Context, anomalyID string) (*model.IntelligenceInsight, error) {
	req := &pb.IntelligenceInsightRequest{AnomalyId: anomalyID}
	res, err := r.GatewayClient.Client.GetIntelligenceInsight(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get intelligence insight: %w", err)
	}

	var deviations []*model.FeatureDeviation
	for _, d := range res.FeatureDeviations {
		deviations = append(deviations, &model.FeatureDeviation{
			FeatureName:          d.FeatureName,
			ShapAttribution:      d.ShapAttribution,
			DeviationDescription: d.DeviationDescription,
		})
	}

	return &model.IntelligenceInsight{
		AnomalyID:         res.AnomalyId,
		ConfidenceScore:   res.ConfidenceScore,
		Reasons:           res.Reasons,
		FeatureDeviations: deviations,
	}, nil
}

// EvaluateReliability is the resolver for the evaluateReliability field.
func (r *queryResolver) EvaluateReliability(ctx context.Context, feederID string, timestamp *string) (*model.ReliabilityResult, error) {
	panic(fmt.Errorf("not implemented: EvaluateReliability - evaluateReliability"))
}

// PredictRisk is the resolver for the predictRisk field.
func (r *queryResolver) PredictRisk(ctx context.Context, feederID string) (*model.RiskPrediction, error) {
	panic(fmt.Errorf("not implemented: PredictRisk - predictRisk"))
}

// DetectAnomaly is the resolver for the detectAnomaly field.
func (r *queryResolver) DetectAnomaly(ctx context.Context, feederID string) (*model.AnomalyDetection, error) {
	panic(fmt.Errorf("not implemented: DetectAnomaly - detectAnomaly"))
}

// RankInterventions is the resolver for the rankInterventions field.
func (r *queryResolver) RankInterventions(ctx context.Context, queryID string) (*model.InterventionRanking, error) {
	panic(fmt.Errorf("not implemented: RankInterventions - rankInterventions"))
}

// OperationalEventStream is the resolver for the operationalEventStream field.
func (r *subscriptionResolver) OperationalEventStream(ctx context.Context) (<-chan *model.AnomalyEvent, error) {
	return r.Subscriptions.Subscribe(ctx)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type (
	mutationResolver     struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
