[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:gateway]
command=/app/backend/services/gateway/gateway-service
directory=/app/backend/services/gateway
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=AUTH_SERVICE_URL="http://127.0.0.1:8081",ALERT_SERVICE_URL="http://127.0.0.1:8006",ENGINE_A_URL="http://127.0.0.1:8001",ASSISTANT_SERVICE_URL="http://127.0.0.1:8005"

[program:auth]
command=/app/backend/services/auth/auth-service
directory=/app/backend/services/auth
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:alerts]
command=/app/backend/services/alerts/alerts-service
directory=/app/backend/services/alerts
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:dashboard-bff]
command=/app/backend/services/dashboard-bff/dashboard-bff-service
directory=/app/backend/services/dashboard-bff
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=GATEWAY_GRPC_URL="127.0.0.1:50051"

[program:engine-a]
command=python main.py
directory=/app/backend/ai-services/engine_a
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:engine-b]
command=python main.py
directory=/app/backend/ai-services/engine_b
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:engine-c]
command=python main.py
directory=/app/backend/ai-services/engine_c
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:engine-d]
command=python main.py
directory=/app/backend/ai-services/engine_d
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:ai-assistant]
command=python main.py
directory=/app/backend/ai-services/ai_assistant
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
