// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID             pgtype.UUID
	Domain         string
	EntityType     string
	EntityID       string
	FeederID       string
	Type           string
	Severity       string
	Message        string
	Metadata       []byte
	Fingerprint    string
	Embedding      []float32
	Status         string
	AcknowledgedAt pgtype.Timestamp
	AcknowledgedBy pgtype.Text
	ResolvedAt     pgtype.Timestamp
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type CreateAlertParams struct {
	Domain      string
	EntityType  string
	EntityID    string
	FeederID    string
	Type        string
	Severity    string
	Message     string
	Metadata    []byte
	Fingerprint string
	Embedding   []float32
}

type UpdateAlertStatusParams struct {
	Status         pgtype.Text
	AcknowledgedAt pgtype.Timestamp
	AcknowledgedBy pgtype.Text
	ResolvedAt     pgtype.Timestamp
	ID             pgtype.UUID
}

type FindSimilarAlertsParams struct {
	Embedding []float32
	Limit     int32
}

type ListActiveAlertsParams struct {
	Limit  int32
	Offset int32
}

type LogInterventionParams struct {
	AlertID     string
	FeederID    string
	OperatorID  string
	ActionTaken string
	Notes       string
	Timestamp   pgtype.Timestamp
}

type DBTX interface {
	Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

func (q *Queries) WithTx(tx pgx.Tx) *Queries {
	return &Queries{db: tx}
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	// TODO: Implement actual SQL query
	return Alert{}, nil
}

func (q *Queries) GetAlertByID(ctx context.Context, id interface{}) (Alert, error) {
	// TODO: Implement actual SQL query
	return Alert{}, pgx.ErrNoRows
}

func (q *Queries) ListActiveAlerts(ctx context.Context, arg ListActiveAlertsParams) ([]Alert, error) {
	// TODO: Implement actual SQL query
	return []Alert{}, nil
}

func (q *Queries) UpdateAlertStatus(ctx context.Context, arg UpdateAlertStatusParams) (Alert, error) {
	// TODO: Implement actual SQL query
	return Alert{}, pgx.ErrNoRows
}

func (q *Queries) FindSimilarAlerts(ctx context.Context, arg FindSimilarAlertsParams) ([]Alert, error) {
	// TODO: Implement actual SQL query
	return []Alert{}, nil
}

func (q *Queries) LogIntervention(ctx context.Context, arg LogInterventionParams) error {
	// TODO: Implement actual SQL query
	return nil
}
