// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createAlert = `-- name: CreateAlert :one
INSERT INTO alerts (
    domain, entity_type, entity_id, feeder_id, type, severity, message, metadata, fingerprint, embedding
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING *;`

const getAlertByID = `-- name: GetAlertByID :one
SELECT * FROM alerts
WHERE id = $1 LIMIT 1;`

const listActiveAlerts = `-- name: ListActiveAlerts :many
SELECT * FROM alerts
WHERE status = 'OPEN' OR status = 'ACKNOWLEDGED'
ORDER BY created_at DESC
LIMIT $1 OFFSET $2;`

const updateAlertStatus = `-- name: UpdateAlertStatus :one
UPDATE alerts
SET 
    status = $1,
    acknowledged_at = COALESCE($2, acknowledged_at),
    acknowledged_by = COALESCE($3, acknowledged_by),
    resolved_at = COALESCE($4, resolved_at)
WHERE id = $5
RETURNING *;`

const findSimilarAlerts = `-- name: FindSimilarAlerts :many
-- Uses the pgvector HNSW index to find semantically similar past alerts
SELECT * FROM alerts
WHERE embedding IS NOT NULL
ORDER BY embedding <-> $1
LIMIT $2;`

const logIntervention = `-- name: LogIntervention :exec
-- Captures operator actions for Engine D's reinforcement learning baseline
INSERT INTO operator_interventions (
    alert_id, feeder_id, operator_id, action_taken, notes, timestamp
) VALUES (
    $1, $2, $3, $4, $5, $6
);`

type CreateAlertParams struct {
	Domain      string
	EntityType  string
	EntityID    string
	FeederID    sql.NullString
	Type        string
	Severity    string
	Message     string
	Metadata    pqtype.NullRawMessage
	Fingerprint string
	Embedding   interface{}
}

type UpdateAlertStatusParams struct {
	Status         string
	AcknowledgedAt sql.NullTime
	AcknowledgedBy uuid.NullUUID
	ResolvedAt     sql.NullTime
	ID             uuid.UUID
}

type FindSimilarAlertsParams struct {
	Embedding interface{}
	Limit     int32
}

type ListActiveAlertsParams struct {
	Limit  int32
	Offset int32
}

type LogInterventionParams struct {
	AlertID     uuid.UUID
	FeederID    string
	OperatorID  string
	ActionTaken string
	Notes       sql.NullString
	Timestamp   time.Time
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	// TODO: Implement actual SQL query
	return Alert{}, nil
}

func (q *Queries) GetAlertByID(ctx context.Context, id uuid.UUID) (Alert, error) {
	// TODO: Implement actual SQL query
	return Alert{}, sql.ErrNoRows
}

func (q *Queries) ListActiveAlerts(ctx context.Context, arg ListActiveAlertsParams) ([]Alert, error) {
	// TODO: Implement actual SQL query
	return []Alert{}, nil
}

func (q *Queries) UpdateAlertStatus(ctx context.Context, arg UpdateAlertStatusParams) (Alert, error) {
	// TODO: Implement actual SQL query
	return Alert{}, sql.ErrNoRows
}

func (q *Queries) FindSimilarAlerts(ctx context.Context, arg FindSimilarAlertsParams) ([]Alert, error) {
	// TODO: Implement actual SQL query
	return []Alert{}, nil
}

func (q *Queries) LogIntervention(ctx context.Context, arg LogInterventionParams) error {
	// TODO: Implement actual SQL query
	return nil
}
