// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AnomalyEvent struct {
	ID          string `json:"id"`
	AreaID      string `json:"areaId"`
	EventType   string `json:"eventType"`
	Severity    string `json:"severity"`
	Timestamp   string `json:"timestamp"`
	Description string `json:"description"`
}

type AreaDetail struct {
	ID               string  `json:"id"`
	Name             string  `json:"name"`
	CurrentRiskScore float64 `json:"currentRiskScore"`
	Status           string  `json:"status"`
}

type DashboardSummary struct {
	OverallReliabilityScore float64 `json:"overallReliabilityScore"`
	ActiveHighRiskAreas     int     `json:"activeHighRiskAreas"`
	TotalActiveAlerts       int     `json:"totalActiveAlerts"`
}

type FeatureDeviation struct {
	FeatureName          string  `json:"featureName"`
	ShapAttribution      float64 `json:"shapAttribution"`
	DeviationDescription string  `json:"deviationDescription"`
}

type IntelligenceInsight struct {
	AnomalyID         string              `json:"anomalyId"`
	ConfidenceScore   float64             `json:"confidenceScore"`
	Reasons           []string            `json:"reasons"`
	FeatureDeviations []*FeatureDeviation `json:"featureDeviations"`
}

type PriorityArea struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	UrgencyRank int     `json:"urgencyRank"`
	RiskScore   float64 `json:"riskScore"`
	Status      string  `json:"status"`
}

type Query struct {
}

type RiskForecastPoint struct {
	Timestamp          string  `json:"timestamp"`
	PredictedRiskScore float64 `json:"predictedRiskScore"`
	IsHistorical       bool    `json:"isHistorical"`
}

type Subscription struct {
}

type TrendDataPoint struct {
	Timestamp string  `json:"timestamp"`
	Value     float64 `json:"value"`
}
